import CryptoKit
import Foundation
import ImageIO
import UIKit
import UniformTypeIdentifiers
import XCTest
@testable import NeutrinoPhotos

// MARK: - TestKeys

/// Installs a real X25519 key pair into the Keychain so the encryption paths can be exercised for
/// what they actually are.
///
/// The crypto is deliberately *not* mocked. The `crypto_box_seal` / secretstream round trip is the
/// part of this app most expensive to get subtly wrong, and a fake that always "decrypts" would
/// assert nothing about it. libsodium's `crypto_box` uses X25519 keys, which is exactly what
/// `Curve25519.KeyAgreement` produces, so a CryptoKit-generated pair is interchangeable with the
/// one the web app exports.
enum TestKeys {

    /// Generates a pair and stores it under the same Keychain keys the app reads.
    @discardableResult
    static func install() -> KeyBundle {
        let priv = Curve25519.KeyAgreement.PrivateKey()
        let bundle = KeyBundle(
            publicKey: base64URL(priv.publicKey.rawRepresentation),
            privateKey: base64URL(priv.rawRepresentation),
            keyVersion: "1"
        )
        KeyImportService.storeKeys(bundle)
        return bundle
    }

    static func remove() {
        KeyImportService.removeKeys()
    }

    /// A valid key-file payload, in the format the web app exports.
    static func keyFileJSON() -> Data {
        let priv = Curve25519.KeyAgreement.PrivateKey()
        let dict = [
            "public_key": base64URL(priv.publicKey.rawRepresentation),
            "private_key": base64URL(priv.rawRepresentation),
            "key_version": "1",
        ]
        return try! JSONSerialization.data(withJSONObject: dict)
    }

    static func base64URL(_ data: Data) -> String {
        data.base64EncodedString()
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "=", with: "")
    }
}

// MARK: - WebVault

/// A key vault produced by the *web* implementation, captured verbatim.
///
/// Generated by running `e2e-crypto`'s own `hash-wasm` and `libsodium-wrappers` over fixed inputs —
/// see `web/packages/e2e-crypto/src/{kdf,vault}.ts` — rather than by this app encrypting something
/// and decrypting it again. That distinction is the entire point: a self-consistent round trip
/// passes just as happily when both halves are wrong together, and the failure mode this guards
/// against is an account that unlocks on the web and not on the phone.
///
/// Regenerate by re-running that script; do not "fix" a failure by editing these constants.
enum WebVault {

    static let password = "correct horse battery staple"

    /// Argon2id: salt `00 01 02 … 0f`, t=3, m=64 MiB, p=1 — the web client's defaults.
    static let argon2ParamsJSON =
        #"{"kdf":"argon2id","salt":"AAECAwQFBgcICQoLDA0ODw","iterations":3,"memoryKiB":65536,"parallelism":1}"#

    /// The KEK those parameters derive from `password`, as hash-wasm computed it.
    static let kekHex = "0d1a3c6523c8f06e4e0af9c515aa5b5448cfebd6838f2d52c3d8b6ef8ddc3c2e"

    static let encryptedMasterKey =
        "bclXsqrnSw0snwX5sVb1UBXdS7kTMHLCtXRrTVPOWBd91Y9ONMla_FY6FLCCHkL0fp65T9B82BpqNgW0LpWZfvB2X7Ny2_w6"

    /// The recovery code, and the *same* master key wrapped under it — which is the property that
    /// matters: every unlock method wraps one master key, so any of them lands on one identity.
    /// Written already normalized, because that is what the client derives from.
    static let recoveryCode = "abcd-efgh"
    static let recoveryEncryptedMasterKey =
        "vsNynVj8z6DGul3Q4jOhsY0rj2SDHuWJtLN06f_yZ5mIw5zMyV79B8RxRgUePPM1A1Y7skV-6jNGt8VcTbFlPAUkUYyuboV5"

    static let encryptedIdentity =
        "qMopQyPKi8lMRyjw044yp--fZpZ7Uyyo5bzxm-CmOZiOvfTSUKlX_Ug_K-QR4LwA_PSRK0qkdnStAp7E9DG-cx9Vm8oWk0rJ"

    static let publicKey  = "rKT4EL17d-ACJum-eHGYLJOe5uEJu_oLDDjQQLy2tBY"
    static let privateKey = "3mBfEeWEWhVLQVr7Bx3XOIZHVhjZCfzYV5zcw2ayXN0"

    /// The vault as `GET /api/v1/auth/keyvault` serves it.
    static func responseJSON(methods: [String] = ["password"], version: Int = 1) -> Data {
        let unlocks = methods.enumerated().map { index, method -> String in
            let params = method == "passkey"
                ? #"{\"kdf\":\"webauthn-prf\",\"credentialId\":\"Y3JlZA\",\"prfSalt\":\"AAECAwQFBgcICQoLDA0ODw\"}"#
                : argon2ParamsJSON.replacingOccurrences(of: "\"", with: "\\\"")
            let wrapped = method == "recovery" ? recoveryEncryptedMasterKey : encryptedMasterKey
            return """
            {"id":"unlock-\(index)","method":"\(method)","label":"\(method.capitalized)",
             "encryptedMasterKey":"\(wrapped)","params":"\(params)",
             "createdAt":"2026-08-01T10:00:00+00:00","lastUsedAt":null}
            """
        }
        return Data("""
        {"encryptedIdentity":"\(encryptedIdentity)","publicKey":"\(publicKey)",
         "version":\(version),"unlocks":[\(unlocks.joined(separator: ","))]}
        """.utf8)
    }

    static var argon2Params: Argon2Params {
        try! JSONDecoder().decode(Argon2Params.self, from: Data(argon2ParamsJSON.utf8))
    }
}

// MARK: - TestTokens

/// Puts an access token in the Keychain so services believe they are signed in.
enum TestTokens {

    /// Decodes to `{"alg":"none","typ":"JWT"}.{"sub":"test-user-id"}.` — a real (if unsigned) JWT
    /// shape rather than an opaque string, because `AccessToken.currentUserID()` reads the `sub`
    /// claim out of it.
    static let userId = "test-user-id"
    static let defaultAccessToken =
        "eyJhbGciOiJub25lIiwidHlwIjoiSldUIn0.eyJzdWIiOiJ0ZXN0LXVzZXItaWQifQ."

    static func install(accessToken: String = TestTokens.defaultAccessToken) {
        KeychainService.save(accessToken, forKey: AuthService.accessTokenKey)
        // Far-future expiry so `refreshTokenIfNeeded` short-circuits and no test accidentally
        // depends on a refresh round trip it did not stub.
        let expiry = ISO8601DateFormatter().string(from: Date().addingTimeInterval(3600))
        KeychainService.save(expiry, forKey: AuthService.tokenExpiryKey)
    }

    static func remove() {
        KeychainService.delete(forKey: AuthService.accessTokenKey)
        KeychainService.delete(forKey: AuthService.refreshTokenKey)
        KeychainService.delete(forKey: AuthService.tokenExpiryKey)
    }
}

// MARK: - TestServer

/// Points the app at a fixed host so assertions on request URLs are stable.
enum TestServer {
    static let host = "https://test.neutrino.local"

    static func use() {
        UserDefaults.standard.set(host, forKey: AuthService.serverHostKey)
    }

    static func reset() {
        UserDefaults.standard.removeObject(forKey: AuthService.serverHostKey)
    }
}

// MARK: - Fixtures

enum Fixture {

    /// A library item with sensible defaults, so a test only states what it cares about.
    static func item(id: String = "photo-1",
                     fileID: String = "file-1",
                     fileName: String = "IMG_0001.jpg",
                     mimeType: String = "image/jpeg",
                     sizeBytes: Int64 = 2_400_000,
                     thumbnailBase64: String? = nil,
                     isStarred: Bool = false,
                     isArchived: Bool = false,
                     captureDate: Date? = Date(timeIntervalSince1970: 1_700_000_000),
                     createdAt: Date = Date(timeIntervalSince1970: 1_700_100_000),
                     metadata: MediaMetadata? = nil) -> MediaItem {
        MediaItem(id: id, fileID: fileID, fileName: fileName, mimeType: mimeType,
                  sizeBytes: sizeBytes, thumbnailBase64: thumbnailBase64,
                  thumbnailMIMEType: thumbnailBase64 == nil ? nil : "image/jpeg",
                  isStarred: isStarred, isArchived: isArchived, captureDate: captureDate,
                  createdAt: createdAt, updatedAt: createdAt, metadata: metadata)
    }

    /// The RFC 3339 shape the Photos endpoints emit (`chrono`'s `to_rfc3339()`).
    static func rfc3339(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss.SSSSSSSSSXXXXX"
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = TimeZone(secondsFromGMT: 0)
        return formatter.string(from: date)
    }

    /// One `PhotoResponse`, as the server serializes it.
    static func photoJSON(id: String = "photo-1",
                          fileID: String = "file-1",
                          fileName: String = "IMG_0001.jpg",
                          mimeType: String = "image/jpeg",
                          sizeBytes: Int = 2_400_000,
                          thumbnail: String? = nil,
                          isStarred: Bool = false,
                          isArchived: Bool = false,
                          captureDate: Date? = Date(timeIntervalSince1970: 1_700_000_000),
                          createdAt: Date = Date(timeIntervalSince1970: 1_700_100_000)) -> String {
        let thumbnailField = thumbnail.map { "\"\($0)\"" } ?? "null"
        let thumbnailMIME = thumbnail == nil ? "null" : "\"image/jpeg\""
        let capture = captureDate.map { "\"\(rfc3339($0))\"" } ?? "null"
        return """
        {"id":"\(id)","fileId":"\(fileID)","fileName":"\(fileName)","mimeType":"\(mimeType)",
         "sizeBytes":\(sizeBytes),"contentUrl":"/api/v1/drive/files/\(fileID)",
         "thumbnail":\(thumbnailField),"thumbnailMimeType":\(thumbnailMIME),
         "isStarred":\(isStarred),"isArchived":\(isArchived),"captureDate":\(capture),
         "createdAt":"\(rfc3339(createdAt))","updatedAt":"\(rfc3339(createdAt))","metadata":null}
        """
    }

    static func listingJSON(_ photos: [String]) -> Data {
        Data("""
        {"photos":[\(photos.joined(separator: ","))],"total":\(photos.count)}
        """.utf8)
    }

    /// One `AlbumResponse`.
    static func albumJSON(id: String = "album-1",
                          title: String = "Trip",
                          isAuto: Bool = false,
                          photoCount: Int = 0,
                          createdAt: Date = Date(timeIntervalSince1970: 1_700_100_000)) -> String {
        """
        {"id":"\(id)","title":"\(title)","description":null,"isAuto":\(isAuto),"personId":null,
         "photoCount":\(photoCount),"createdAt":"\(rfc3339(createdAt))",
         "updatedAt":"\(rfc3339(createdAt))"}
        """
    }
}

// MARK: - TestImages

/// Real image data, because everything the rendition ladder does is ImageIO reading actual pixels.
/// A `Data("not a jpeg")` would exercise the error path and nothing else.
enum TestImages {

    /// A JPEG with two flat regions, so a downscale still has something to encode.
    ///
    /// Rendered at scale 1 so `size` is pixels rather than points — otherwise the same test asserts
    /// against a 2× image on one simulator and a 3× image on another.
    static func jpeg(size: CGFloat = 64, quality: CGFloat = 0.9) -> Data {
        let format = UIGraphicsImageRendererFormat()
        format.scale = 1
        let renderer = UIGraphicsImageRenderer(size: CGSize(width: size, height: size),
                                               format: format)
        let image = renderer.image { context in
            UIColor.systemTeal.setFill()
            context.fill(CGRect(x: 0, y: 0, width: size, height: size))
            UIColor.black.setFill()
            context.fill(CGRect(x: 0, y: 0, width: size / 2, height: size / 2))
        }
        return image.jpegData(compressionQuality: quality) ?? Data()
    }

    /// The same picture with real EXIF, TIFF, and GPS blocks written into it.
    ///
    /// Written through `CGImageDestination` rather than hand-assembled, so what the extractor reads
    /// back is a genuine JPEG APP1 segment laid out by the same framework a camera's file would be
    /// parsed with. A fixture that faked the dictionary would assert that ImageIO can round-trip a
    /// dictionary, which is not the thing under test.
    ///
    /// - Parameters:
    ///   - latitude: the *magnitude*, as EXIF stores it. The hemisphere is `latitudeRef`, which is
    ///     the half a naive reader drops — see `MediaMetadataExtractor.coordinate(from:)`.
    static func jpegWithMetadata(size: CGFloat = 64,
                                 make: String? = "Apple",
                                 model: String? = "iPhone 15 Pro",
                                 lens: String? = "iPhone 15 Pro back triple camera 6.765mm f/1.78",
                                 exposureTime: Double? = 1.0 / 120,
                                 fNumber: Double? = 1.78,
                                 iso: Int? = 200,
                                 focalLength: Double? = 6.765,
                                 dateTimeOriginal: String? = "2024:06:15 14:25:36",
                                 latitude: Double? = nil, latitudeRef: String = "N",
                                 longitude: Double? = nil, longitudeRef: String = "E") -> Data {
        guard let source = CGImageSourceCreateWithData(jpeg(size: size) as CFData, nil),
              let image = CGImageSourceCreateImageAtIndex(source, 0, nil) else { return Data() }

        var exif: [CFString: Any] = [:]
        if let exposureTime { exif[kCGImagePropertyExifExposureTime] = exposureTime }
        if let fNumber { exif[kCGImagePropertyExifFNumber] = fNumber }
        if let iso { exif[kCGImagePropertyExifISOSpeedRatings] = [iso] }
        if let focalLength { exif[kCGImagePropertyExifFocalLength] = focalLength }
        if let dateTimeOriginal { exif[kCGImagePropertyExifDateTimeOriginal] = dateTimeOriginal }
        if let lens { exif[kCGImagePropertyExifLensModel] = lens }

        var tiff: [CFString: Any] = [:]
        if let make { tiff[kCGImagePropertyTIFFMake] = make }
        if let model { tiff[kCGImagePropertyTIFFModel] = model }

        var gps: [CFString: Any] = [:]
        if let latitude {
            gps[kCGImagePropertyGPSLatitude] = latitude
            gps[kCGImagePropertyGPSLatitudeRef] = latitudeRef
        }
        if let longitude {
            gps[kCGImagePropertyGPSLongitude] = longitude
            gps[kCGImagePropertyGPSLongitudeRef] = longitudeRef
        }

        var properties: [CFString: Any] = [:]
        if !exif.isEmpty { properties[kCGImagePropertyExifDictionary] = exif }
        if !tiff.isEmpty { properties[kCGImagePropertyTIFFDictionary] = tiff }
        if !gps.isEmpty { properties[kCGImagePropertyGPSDictionary] = gps }

        let output = NSMutableData()
        guard let destination = CGImageDestinationCreateWithData(
            output, UTType.jpeg.identifier as CFString, 1, nil) else { return Data() }
        CGImageDestinationAddImage(destination, image, properties as CFDictionary)
        guard CGImageDestinationFinalize(destination) else { return Data() }
        return output as Data
    }
}

// MARK: - DeviceAsset fixture

extension DeviceAsset {

    /// One `PHAsset`'s worth of facts, without a photo library.
    ///
    /// `PHAsset` cannot be constructed outside the Photos framework and a simulator has no library
    /// worth fetching from, so everything downstream of ``DevicePhotoLibrary`` is written against
    /// this value type rather than against the framework — which is the reason `DeviceAsset` exists
    /// at all.
    static func fixture(localIdentifier: String = "ABCD-1234/L0/001",
                        creationDate: Date? = Date(timeIntervalSince1970: 1_600_000_000),
                        coordinate: (latitude: Double, longitude: Double)? = nil,
                        isFavorite: Bool = false,
                        isLivePhoto: Bool = false,
                        isRAW: Bool = false,
                        subtypes: [String] = [],
                        pixelWidth: Int? = 4032,
                        pixelHeight: Int? = 3024) -> DeviceAsset {
        DeviceAsset(localIdentifier: localIdentifier, creationDate: creationDate,
                    coordinate: coordinate, isFavorite: isFavorite, isLivePhoto: isLivePhoto,
                    isRAW: isRAW, subtypes: subtypes,
                    pixelWidth: pixelWidth, pixelHeight: pixelHeight)
    }
}

// MARK: - Temp directories

extension XCTestCase {

    /// A unique empty directory, removed when the test finishes.
    func makeTemporaryDirectory(file: StaticString = #filePath, line: UInt = #line) -> URL {
        let url = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("NeutrinoPhotosTests-\(UUID().uuidString)", isDirectory: true)
        do {
            try FileManager.default.createDirectory(at: url, withIntermediateDirectories: true)
        } catch {
            XCTFail("Could not create temp directory: \(error)", file: file, line: line)
        }
        addTeardownBlock {
            try? FileManager.default.removeItem(at: url)
        }
        return url
    }

    /// A `UserDefaults` suite of its own, removed when the test finishes, so a settings test cannot
    /// disturb the simulator's real preferences or another test's.
    func makeTemporaryDefaults(file: StaticString = #filePath, line: UInt = #line) -> UserDefaults {
        let name = "NeutrinoPhotosTests-\(UUID().uuidString)"
        guard let defaults = UserDefaults(suiteName: name) else {
            XCTFail("Could not create UserDefaults suite", file: file, line: line)
            return .standard
        }
        addTeardownBlock {
            defaults.removePersistentDomain(forName: name)
        }
        return defaults
    }
}
