import Foundation
import ImageIO
import Sodium
import UIKit
import os.log

// MARK: - MediaContentError

enum MediaContentError: LocalizedError {
    case noEncryptionKey
    case encryptionFailed
    case decryptionFailed
    case notAuthenticated
    case undecodable

    var errorDescription: String? {
        switch self {
        case .noEncryptionKey:
            return "No encryption key found. Import your key to open originals."
        case .encryptionFailed:
            return "Failed to encrypt the photo."
        case .decryptionFailed:
            return "Failed to decrypt the photo. It may have been encrypted with a different key."
        case .notAuthenticated:
            return "You are not signed in."
        case .undecodable:
            return "That file isn't an image this app can display."
        }
    }
}

// MARK: - MediaContentService

/// The bytes: downloading and decrypting an original, and encrypting and uploading a new one.
///
/// Mirrors the E2EE protocol the web app uses for a Drive upload exactly — XChaCha20-Poly1305
/// secretstream for the content, `crypto_box_seal` for the per-file key — so a photograph imported
/// here opens on the web and vice versa.
///
/// ## What the grid does *not* need
///
/// Nothing here is involved in drawing the timeline. A Drive file carries a small plaintext cover
/// thumbnail, generated by whichever client uploaded it, and that is what a grid cell draws. Only
/// opening an item at full size comes through this service — which is why the library is browsable
/// before an encryption key has been imported, and why a 500-photo timeline is not 500 downloads.
///
/// ## What is never logged
///
/// No method here logs a DEK, a sealed DEK, or plaintext. File ids and byte counts are the most
/// this will say about a photograph, because `os.log` messages persist in the system log store and
/// a key written there outlives the process that leaked it.
@MainActor
final class MediaContentService: ObservableObject {

    // MARK: - Dependencies

    private let api: APIClient

    // MARK: - Private

    private let logger = Logger(subsystem: Bundle.main.bundleIdentifier ?? "NeutrinoPhotos",
                                category: "MediaContentService")

    /// Decoded originals, keyed by file id and the size they were decoded at.
    ///
    /// `NSCache` rather than a dictionary because it evicts under memory pressure, which is the
    /// whole point: a viewer swiped through twenty photographs holds twenty full-screen bitmaps
    /// otherwise, and the OS kills the app rather than asking.
    private let imageCache: NSCache<NSString, UIImage> = {
        let cache = NSCache<NSString, UIImage>()
        cache.totalCostLimit = 128 * 1024 * 1024   // bytes of bitmap, not pixels
        return cache
    }()

    /// Decrypted videos, written to disk because `AVPlayer` plays from a URL and a video is far too
    /// large to hold as `Data` in memory. Cleared with the image cache.
    private var videoFiles: [String: URL] = [:]

    /// Drive's own endpoints, unlike the Photos ones, are not uniformly camelCase — the sibling
    /// apps all read them with snake-case conversion, and a key that is already camelCase passes
    /// through it unchanged, so this is the safe spelling for both.
    private static let driveDecoder = DriveDate.makeDecoder(convertFromSnakeCase: true)

    private var cacheDirectory: URL {
        FileManager.default.temporaryDirectory.appendingPathComponent("media", isDirectory: true)
    }

    // MARK: - Init

    init(api: APIClient) {
        self.api = api
    }

    // MARK: - Reading

    /// Downloads and decrypts an item's original.
    ///
    /// A file with no key ref is returned as it stands: that is a picture uploaded before E2EE, or
    /// by something that never sealed a key, and the download already *is* the image. The web app's
    /// resolver makes the same allowance, so the two agree on which files are readable.
    func originalData(for item: MediaItem) async throws -> Data {
        let ciphertext = try await api.data(path: "/api/v1/drive/files/\(item.fileID)")

        guard let sealedDEK = try await fetchSealedDEKIfPresent(fileID: item.fileID) else {
            logger.debug("originalData: \(item.fileID, privacy: .public) has no key ref, using bytes as they are")
            return ciphertext
        }
        let dek = try unsealDEK(sealedDEK)
        // One push covering the whole file — what this app and the web client both write today. The
        // chunked framing `MediaCrypto` can also read is announced in a file's encrypted metadata,
        // and nothing writes it until the large-video path needs it.
        let plaintext = Data(try MediaCrypto.decrypt(ciphertext, dek: dek))
        logger.debug("originalData: \(item.fileID, privacy: .public) (\(plaintext.count) bytes)")
        return plaintext
    }

    /// The item as a displayable image, decoded no larger than `maxPixels` on its longest edge.
    ///
    /// Decoded through ImageIO rather than `UIImage(data:)`, which holds the whole picture as a
    /// bitmap to draw it: about 48 MB for a 12-megapixel photograph, none of which is needed to
    /// fill a phone screen. Downsampling at decode is what makes storing originals affordable on a
    /// device.
    func image(for item: MediaItem, maxPixels: CGFloat = 2048) async throws -> UIImage {
        let key = "\(item.fileID)@\(Int(maxPixels))" as NSString
        if let cached = imageCache.object(forKey: key) { return cached }

        let data = try await originalData(for: item)
        guard let image = Self.downsample(data: data, maxPixels: maxPixels) else {
            throw MediaContentError.undecodable
        }
        imageCache.setObject(image, forKey: key, cost: Self.bitmapCost(of: image))
        return image
    }

    /// A local file holding the item's decrypted bytes, for `AVPlayer`.
    ///
    /// Written into the temporary directory, which the system reclaims — a decrypted original is
    /// exactly the thing not to leave in Documents, where it would be backed up and would outlive
    /// the reason it was decrypted.
    func localURL(for item: MediaItem) async throws -> URL {
        if let existing = videoFiles[item.fileID],
           FileManager.default.fileExists(atPath: existing.path) {
            return existing
        }

        let data = try await originalData(for: item)
        try FileManager.default.createDirectory(at: cacheDirectory, withIntermediateDirectories: true)
        // Named for the Drive file id and the original's extension: `AVPlayer` picks its
        // demuxer from the path extension, so a `.mov` written as `.dat` simply does not play.
        let url = cacheDirectory.appendingPathComponent("\(item.fileID).\(Self.fileExtension(for: item))")
        try data.write(to: url, options: .atomic)
        videoFiles[item.fileID] = url
        return url
    }

    // MARK: - Writing

    /// Encrypts and uploads a picture, returning the Drive file id it was stored under.
    ///
    /// Registering it as a *photo* is a separate call — see
    /// ``PhotoLibraryService/register(fileID:captureDate:)``. The split is the server's: Drive owns
    /// the bytes, the Photos service owns the library, and an upload that failed to register leaves
    /// a file rather than a half-made photograph.
    ///
    /// No `folder_id` is sent, so the file lands in the account's Drive root. That is where the web
    /// app puts an uploaded photograph, and its default library listing is root-scoped
    /// (`/drive/folders/{rootId}?type=photo`) — filing pictures into a tidy subfolder here would
    /// make them invisible there.
    ///
    /// - Parameter thumbnailBase64: the plaintext preview to store alongside the ciphertext. The
    ///   server cannot make one itself: what it receives is encrypted and the key never leaves the
    ///   device. A photograph uploaded without a preview shows as a blank icon in every grid,
    ///   including this app's.
    func upload(data: Data, fileName: String, mimeType: String, thumbnailBase64: String?,
                onProgress: (@MainActor (Double) -> Void)? = nil) async throws -> String {
        let dek = MediaCrypto.newDEK()
        let ciphertext = try MediaCrypto.encrypt(Bytes(data), dek: dek)
        let encryptedMetadata = try MediaCrypto.encryptMetadata(name: fileName, mimeType: mimeType,
                                                                dek: dek)
        let sealedFileKey = try sealDEK(dek)

        var form = MultipartFormBody()
        form.appendField(name: "encrypted_metadata", value: encryptedMetadata)
        // Written *before* the file part: the server reads the multipart stream in order and stops
        // at the file, so a field that follows the bytes is one it never sees.
        form.appendField(name: "thumbnail_b64", value: thumbnailBase64)
        form.appendFile(name: "file", fileName: fileName, mimeType: mimeType, data: ciphertext)

        let response = try await api.upload(method: "POST", path: "/api/v1/drive/files/upload",
                                            contentType: form.contentType, body: form.finalized(),
                                            onProgress: onProgress)
        let created = try Self.driveDecoder.decode(APIFileResponse.self, from: response)

        // The upload endpoint takes ciphertext, not the sealed key, so the key ref is a second
        // call — and a picture whose key never stored is one nothing can ever open. Allowed to
        // throw rather than being fire-and-forget.
        _ = try await api.send(method: "PUT", path: "/api/v1/drive/files/\(created.id)/key",
                               json: APIStoreKeyRequest(encryptedFileKey: sealedFileKey))
        logger.debug("upload succeeded: id=\(created.id, privacy: .public) (\(data.count) bytes)")
        return created.id
    }

    // MARK: - Cache

    /// Bytes currently held on disk by decrypted videos.
    func cacheSizeOnDisk() -> Int64 {
        guard let contents = try? FileManager.default.contentsOfDirectory(
            at: cacheDirectory, includingPropertiesForKeys: [.fileSizeKey]) else { return 0 }
        return contents.reduce(into: Int64(0)) { total, url in
            total += Int64((try? url.resourceValues(forKeys: [.fileSizeKey]).fileSize) ?? 0)
        }
    }

    func clearCache() {
        imageCache.removeAllObjects()
        videoFiles.removeAll()
        try? FileManager.default.removeItem(at: cacheDirectory)
        logger.debug("cache cleared")
    }

    // MARK: - Crypto
    //
    // The primitives themselves live in `MediaCrypto`, which has no actor and no networking so it
    // can be called off the main thread and asserted on its own. What stays here is the part that
    // needs the Keychain: which key pair a DEK is sealed to.

    /// Seals `dek` to the account's stored Curve25519 public key (`crypto_box_seal`).
    func sealDEK(_ dek: Bytes) throws -> String {
        guard let publicKey = Self.storedKey(KeyImportService.publicKeyKeychainKey) else {
            throw MediaContentError.noEncryptionKey
        }
        return try MediaCrypto.seal(dek: dek, toPublicKey: publicKey)
    }

    /// Reverses ``sealDEK(_:)`` with the stored private key (`crypto_box_seal_open`).
    func unsealDEK(_ sealedBase64: String) throws -> Bytes {
        guard let publicKey = Self.storedKey(KeyImportService.publicKeyKeychainKey),
              let secretKey = Self.storedKey(KeyImportService.privateKeyKeychainKey) else {
            logger.error("unsealDEK: no stored key pair, or the stored key is not valid Base64URL")
            throw MediaContentError.noEncryptionKey
        }
        do {
            return try MediaCrypto.openDEK(sealedBase64, publicKey: publicKey, secretKey: secretKey)
        } catch {
            logger.error("unsealDEK: the seal was not made to this device's public key")
            throw error
        }
    }

    private static func storedKey(_ keychainKey: String) -> Bytes? {
        KeychainService.load(forKey: keychainKey).flatMap(KeyVaultCrypto.decodeBase64URL)
    }

    // MARK: - Private helpers

    /// The sealed DEK for a file, or nil when the server has none stored for this caller.
    ///
    /// `GET /files/{id}/key` answers 404 for that case (`get_file_key` in
    /// `src/drive/encryption/api.rs`), which is a fact about the file rather than a failure.
    private func fetchSealedDEKIfPresent(fileID: String) async throws -> String? {
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        let response: APIKeyResponse? = try await api.getIfPresent(
            "/api/v1/drive/files/\(fileID)/key", decoder: decoder)
        return response?.encryptedFileKey
    }

    /// Decodes at most `maxPixels` on the longest edge.
    nonisolated static func downsample(data: Data, maxPixels: CGFloat) -> UIImage? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil) else { return nil }
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            // Without this a photograph taken in portrait displays sideways: the rotation lives in
            // the file's EXIF orientation, which a re-encoded bitmap does not carry.
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceShouldCacheImmediately: true,
            kCGImageSourceThumbnailMaxPixelSize: maxPixels,
        ]
        guard let cgImage = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) else {
            return nil
        }
        return UIImage(cgImage: cgImage)
    }

    private static func bitmapCost(of image: UIImage) -> Int {
        guard let cgImage = image.cgImage else { return 0 }
        return cgImage.bytesPerRow * cgImage.height
    }

    private static func fileExtension(for item: MediaItem) -> String {
        if let dot = item.fileName.lastIndex(of: "."), dot != item.fileName.startIndex {
            return String(item.fileName[item.fileName.index(after: dot)...])
        }
        // Falls back to the MIME subtype: "video/quicktime" is not a usable extension, but
        // "video/mp4" is, and either beats no extension at all.
        return item.mimeType.split(separator: "/").last.map(String.init) ?? "dat"
    }
}

// MARK: - API Models

private struct APIFileResponse: Decodable {
    let id: String
    let name: String
    let sizeBytes: Int64
    let mimeType: String

    private enum CodingKeys: String, CodingKey {
        case id, name, sizeBytes, mimeType
    }
}

private struct APIKeyResponse: Decodable {
    let encryptedFileKey: String
}

private struct APIStoreKeyRequest: Encodable {
    let encryptedFileKey: String
}
